repositories:
  - name: dts
    url: https://helm.dts-stn.com
  # helm-git powered repository: You can treat any Git repository as a charts repository
  - name: instabenefitserver
    url: git+https://{{ requiredEnv "GITHUB_USER" }}:{{ requiredEnv "GITHUB_TOKEN" }}@github.com/DTS-STN/InstaBenefitServer@helm/charts?ref=master
  {{- if or (eq .Environment.Name "prod-blue") (eq .Environment.Name "prod-green") }}
context: EsDCDTSRG-K8S
  {{ else }}
context: EsDCDTSDevRG-K8S
  {{ end }}

environments:
  dev:

releases:
  - name: instabenefitserver-{{ .Environment.Name }}
    chart: ../helm/charts/instabenefitserver
    version: 0.0.1
    values:
      - overrides/instabenefitserver.yaml.gotmpl
    labels:
      category: dts
      app: instabenefitserver
      tier: server
    namespace: instabenefitserver-{{ .Environment.Name }}
    installed: true
    wait: false
    force: false