FROM node:lts-alpine
ENV NODE_ENV 'production'
ENV NODE_TLS_REJECT_UNAUTHORIZED 0
ENV CURAM_API ''
ENV USER_SERVICE_API ''
ENV BENEFIT_SERVICE_API ''
ENV KEYCLOAK_ENDPOINT ''
ENV KEYCLOAK_CLIENT_ID ''
ENV KEYCLOAK_REALM ''
ENV KEYCLOAK_CLIENT_SECRET ''
COPY ./ ./
RUN npm install --only=prod
EXPOSE 3000
CMD ["npm", "start"]
